version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard
  my-tb-gateway:
    restart: always
    image: "thingsboard/tb-gateway"
    volumes:
      - .tb-gateway/config:/thingsboard_gateway/config
      - .tb-gateway/logs:/thingsboard_gateway/logs
      - .tb-gateway/extensions:/thingsboard_gateway/extensions
volumes:
  mytb-data:
    external: true
  mytb-logs:
    external: true
